/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;
import server.Connectivity;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author vampire
 */
public class LoginPage extends javax.swing.JFrame {

     Connection conn = null;
    ResultSet rs = null;
    PreparedStatement  pst = null;
    static String user;
    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        signup = new javax.swing.JButton();
        hidepassword = new javax.swing.JButton();
        seepassword = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 1200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 99, 105, 27));

        jTextFieldusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 98, 140, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 158, 105, 30));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 159, 140, -1));

        login.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 113, 30));

        signup.setFont(new java.awt.Font("Ubuntu", 0, 19)); // NOI18N
        signup.setText("SignUp");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 100, 30));

        hidepassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eye-with-a-diagonal-line-interface-symbol-for-invisibility.png"))); // NOI18N
        hidepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hidepasswordActionPerformed(evt);
            }
        });
        getContentPane().add(hidepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 40, 30));

        seepassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eye-close-up.png"))); // NOI18N
        seepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seepasswordActionPerformed(evt);
            }
        });
        getContentPane().add(seepassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 40, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldusernameActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
        new SignUp().setVisible(true);
        dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        conn = Connectivity.connect();
        //String query = "select * from tabled where username=? and password=?" ;
        try
        {
            Statement s = conn.createStatement();
            user = jTextFieldusername.getText();
           // userName = user;
            String pass = jPasswordField.getText();
             String query = "select * from tabled where username='"+user+ "'and password='"+pass+"'";
           // PreparedStatement pst = conn.prepareStatement(query);
            //pst.setString(1,jTextFieldusername.getText());
            //pst.setString(2,jPasswordField.getText());
            
            rs = s.executeQuery(query);
            jTextFieldusername.setText("");
            jPasswordField.setText("");
            
            
            if(rs.next())
            {
                new FrontPage().setVisible(true);
                dispose();
               //JOptionPane.showMessageDialog(null,"Login Successful");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Login Failed ");
            }
            
            
                
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_loginActionPerformed

    private void hidepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hidepasswordActionPerformed
        // TODO add your handling code here:
        //jPasswordField.setVisible(false);
        //if(!seepassword.isSelected())
            jPasswordField.setEchoChar('*');
        
    }//GEN-LAST:event_hidepasswordActionPerformed

    private void seepasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seepasswordActionPerformed
            // TODO add your handling code here:
            jPasswordField.setEchoChar((char)0);
    }//GEN-LAST:event_seepasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }
    
     @Override
   public  String getName()
    {
       return user; 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hidepassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldusername;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton login;
    private javax.swing.JButton seepassword;
    private javax.swing.JButton signup;
    // End of variables declaration//GEN-END:variables
}
